[WIP] Fileserver
Mexator/Go-vno pull request #2
Opened 2020-10-04 10:02 UTC by Mexator

2020-10-04 10:11 UTC, Mexator commented on pkg/fileserver/fileserver.go
> +	err := config.ReadConfig(&conf, "config.json")
Я хз как это пофиксить, но os.Open() ищет конфиг файл в рабочей директории

2020-10-04 11:04 UTC, i1i1 requested changes

2020-10-04 11:04 UTC, i1i1 commented on api/proto/fileserver.proto
> +	rpc ReportDiskSpace(Empty) returns (DiskSpaceResponse) {}
Может пофиг?

2020-10-04 11:04 UTC, i1i1 commented on api/proto/fileserver.proto
> +	int64 blockSizeBytes = 3;
Сверху

2020-10-04 11:04 UTC, i1i1 commented on pkg/fileserver/config.json
> +    "files_dir": "/var/data"
Мб не конфигом а флагом из командной строки?

2020-10-04 11:04 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +	"../config"
Лучше референсить через github.com/Mexator ...

2020-10-04 11:04 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +	err := config.ReadConfig(&conf, "config.json")
Менять директорию. Вообще можно флагом из cli

2020-10-04 11:15 UTC, Mexator commented on api/proto/fileserver.proto
> +	rpc ReportDiskSpace(Empty) returns (DiskSpaceResponse) {}
Мне кажется, нет. Как минимум это будет плюсом на защите и несложно имплементится

2020-10-04 11:16 UTC, Mexator commented on pkg/fileserver/config.json
> +    "files_dir": "/var/data"
Для длинных списков настроек конфиг удобнее. Давай так оставим

2020-10-04 11:55 UTC, i1i1 commented on pkg/fileserver/config.json
> +    "files_dir": "/var/data"
А у нас их много будет?

2020-10-05 21:10 UTC, i1i1 approved these changes

2020-10-05 21:10 UTC, i1i1 commented on api/proto/fileserver.proto
> +	bool ok = 1;
В грпц можно скидывать ошибки, поэтому не имеет смысла добавлять ок

2020-10-05 21:10 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +func (server FileServer) Remove(ctx context.Context,
Стиль!

2020-10-05 21:10 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +func (server FileServer) Create(ctx context.Context,
Стиль

2020-10-05 21:10 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +func (server FileServer) Write(ctx context.Context,
Стиль!

2020-10-05 21:10 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +type fileServerConfig struct {
Конфиг из одного поля кажется излишним. Можно давать его из cli

2020-10-05 21:10 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +		return errors.New("Can not open server catalog:" + err.Error())
Errors.wrap

2020-10-05 21:10 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +		return errors.New(path + "has invalid permissions or is not a " +
Сверху

2020-10-05 21:10 UTC, i1i1 commented on pkg/fileserver/fileserver.go
> +		return errors.New("Can not create server catalog:" + err.Error())
Сверху

2020-10-05 21:10 UTC, i1i1 commented on cmd/fileserver/main.go
> +	isNotDir := !info.IsDir()
notIsDir

2020-10-05 21:11 UTC, merged